# Generated by Django 5.0.7 on 2024-10-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstacoesMoveisIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('afectos_planos_pos_pagos', models.IntegerField()),
                ('afectos_planos_pos_pagos_utilizacao', models.IntegerField()),
                ('afectos_planos_pre_pagos', models.IntegerField()),
                ('afectos_planos_pre_pagos_utilizacao', models.IntegerField()),
                ('associados_situacoes_especificas', models.IntegerField(blank=True, null=True)),
                ('outros_residuais', models.IntegerField(blank=True, null=True)),
                ('sms', models.IntegerField()),
                ('mms', models.IntegerField(blank=True, null=True)),
                ('mobile_tv', models.IntegerField(blank=True, null=True)),
                ('roaming_internacional_out_parc_roaming_out', models.IntegerField()),
                ('banda_larga_movel_3g_4g', models.IntegerField()),
                ('utilizadores_5g_upgrades', models.IntegerField()),
                ('utilizadores_servico_acesso_internet_banda_larga', models.IntegerField()),
                ('utilizadores_placas_box', models.IntegerField()),
                ('utilizadores_placas_usb', models.IntegerField()),
                ('utilizadores_servico_4g', models.IntegerField()),
                ('utilizadores_servico_banda_larga', models.IntegerField()),
                ('utilizadores_placas_box_banda_larga', models.IntegerField()),
                ('utilizadores_placas_usb_banda_larga', models.IntegerField()),
                ('numero_utilizadores_mulher', models.IntegerField()),
                ('numero_utilizadores_homem', models.IntegerField()),
                ('total_carregamentos_mulher', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_carregamentos_homem', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_levantamentos_mulher', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_levantamentos_homem', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_transferencias_mulher', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_transferencias_homem', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'unique_together': {('ano', 'mes')},
            },
        ),
    ]
