# Generated by Django 5.0.7 on 2024-07-12 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaxaPenetracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(max_length=10)),
                ('ano', models.IntegerField()),
                ('taxa_penetracao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taxa_penetracao_3g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taxa_penetracao_4g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numero_estacoes', models.IntegerField()),
                ('variacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VolumeNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(max_length=10)),
                ('ano', models.IntegerField()),
                ('volume_mtn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume_orange', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='EstacoesMoveisEfetivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(max_length=10)),
                ('ano', models.IntegerField()),
                ('numero_estacoes', models.IntegerField()),
                ('operadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.operadora')),
            ],
        ),
        migrations.CreateModel(
            name='EmpregoSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(max_length=10)),
                ('ano', models.IntegerField()),
                ('emprego_direto', models.IntegerField()),
                ('emprego_indireto', models.IntegerField()),
                ('nacionais', models.IntegerField()),
                ('homens', models.IntegerField()),
                ('mulheres', models.IntegerField()),
                ('operadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.operadora')),
            ],
        ),
        migrations.CreateModel(
            name='QuotaMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(max_length=10)),
                ('ano', models.IntegerField()),
                ('quota_estacoes_moveis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('operadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.operadora')),
            ],
        ),
        migrations.CreateModel(
            name='TrafegoNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(max_length=10)),
                ('ano', models.IntegerField()),
                ('trafego_on_net', models.BigIntegerField()),
                ('trafego_off_net', models.BigIntegerField()),
                ('trafego_internacional_saida', models.BigIntegerField()),
                ('trafego_internacional_entrada', models.BigIntegerField()),
                ('trafego_roaming_in', models.BigIntegerField()),
                ('trafego_roaming_out', models.BigIntegerField()),
                ('operadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.operadora')),
            ],
        ),
    ]
