# Generated by Django 5.0.7 on 2024-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxapenetracao',
            name='numero_estacoes_3g',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxapenetracao',
            name='numero_estacoes_4g',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxapenetracao',
            name='variacao_3g',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxapenetracao',
            name='variacao_4g',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxapenetracao',
            name='taxa_penetracao_3g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='taxapenetracao',
            name='taxa_penetracao_4g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
