# Generated by Django 5.0.7 on 2024-07-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0002_taxapenetracao_numero_estacoes_3g_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafegonacional',
            options={'ordering': ['-ano', '-trimestre'], 'verbose_name': 'Tráfego Nacional', 'verbose_name_plural': 'Tráfegos Nacionais'},
        ),
        migrations.RemoveField(
            model_name='trafegonacional',
            name='operadora',
        ),
        migrations.RemoveField(
            model_name='trafegonacional',
            name='trafego_internacional_entrada',
        ),
        migrations.RemoveField(
            model_name='trafegonacional',
            name='trafego_internacional_saida',
        ),
        migrations.RemoveField(
            model_name='trafegonacional',
            name='trafego_off_net',
        ),
        migrations.RemoveField(
            model_name='trafegonacional',
            name='trafego_on_net',
        ),
        migrations.RemoveField(
            model_name='trafegonacional',
            name='trafego_roaming_in',
        ),
        migrations.RemoveField(
            model_name='trafegonacional',
            name='trafego_roaming_out',
        ),
        migrations.AddField(
            model_name='trafegonacional',
            name='entrada_internacional',
            field=models.BigIntegerField(default=0, verbose_name='Entrada Internacional'),
        ),
        migrations.AddField(
            model_name='trafegonacional',
            name='off_net',
            field=models.BigIntegerField(default=0, verbose_name='Off-net (saída)'),
        ),
        migrations.AddField(
            model_name='trafegonacional',
            name='off_net_entrada',
            field=models.BigIntegerField(default=0, verbose_name='Off-net (entrada)'),
        ),
        migrations.AddField(
            model_name='trafegonacional',
            name='on_net',
            field=models.BigIntegerField(default=0, verbose_name='On-net'),
        ),
        migrations.AddField(
            model_name='trafegonacional',
            name='roaming_in',
            field=models.BigIntegerField(default=0, verbose_name='Roaming in'),
        ),
        migrations.AddField(
            model_name='trafegonacional',
            name='roaming_out',
            field=models.BigIntegerField(default=0, verbose_name='Roaming out'),
        ),
        migrations.AddField(
            model_name='trafegonacional',
            name='saida_internacional',
            field=models.BigIntegerField(default=0, verbose_name='Saída Internacional'),
        ),
        migrations.AddField(
            model_name='trafegonacional',
            name='total_trafego',
            field=models.BigIntegerField(default=0, verbose_name='Total Tráfego'),
        ),
    ]
