# Generated by Django 5.0.7 on 2024-07-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0003_alter_trafegonacional_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafegonacional',
            name='total_trafego',
        ),
        migrations.AddField(
            model_name='trafegonacional',
            name='total_originadas',
            field=models.BigIntegerField(default=0, verbose_name='Total Originadas'),
        ),
        migrations.AddField(
            model_name='trafegonacional',
            name='total_roaming',
            field=models.BigIntegerField(default=0, verbose_name='Total Roaming'),
        ),
        migrations.AddField(
            model_name='trafegonacional',
            name='total_terminadas',
            field=models.BigIntegerField(default=0, verbose_name='Total Terminadas'),
        ),
    ]
