# Generated by Django 5.0.7 on 2024-07-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0004_remove_trafegonacional_total_trafego_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafegonacional',
            name='total_originadas',
        ),
        migrations.RemoveField(
            model_name='trafegonacional',
            name='total_roaming',
        ),
        migrations.RemoveField(
            model_name='trafegonacional',
            name='total_terminadas',
        ),
    ]
