# Generated by Django 5.0.7 on 2024-07-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0005_remove_trafegonacional_total_originadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumenegocio',
            name='percentagem_mtn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='volumenegocio',
            name='percentagem_orange',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='volumenegocio',
            name='volume_global',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='volumenegocio',
            name='volume_mtn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='volumenegocio',
            name='volume_orange',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
