# Generated by Django 5.0.7 on 2024-12-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_anuais', '0002_alter_dadosanuais_assinantes_3g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosanuais',
            name='operadora',
            field=models.CharField(choices=[('MTN', 'MTN'), ('ORANGE', 'Orange')], max_length=10),
        ),
    ]
