# Generated by Django 5.0.7 on 2025-04-07 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_anuais', '0004_fix_operadora_relation'),
        ('dados_anuais', '0005_update_fields'),
    ]

    operations = [
    ]
